name: Helmfile

on:
  push: {}

jobs:

  regression:

    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/aservo/helmfile:0.143.0

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Versions
      run: |
        helmfile version
        helm version

    - name: Helmfile Template
      run: helmfile template

  working:

    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/aservo/helmfile:0.0.13

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Versions
      run: |
        helmfile version
        helm version

    - name: Helmfile Template
      run: helmfile template
